version: "3.6"

services:

  music:
    # image: ghcr.io/danielkoomen/webapp
    build: .
    volumes:
      - type: bind
        source: ./music
        target: /music
      - type: bind
        source: ./data
        target: /data
    user: "1000"
    environment:
      TZ: Europe/Amsterdam

  music-nginx:
    # image: ghcr.io/danielkoomen/webapp:nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:8080
    user: "1000"
    environment:
      TZ: Europe/Amsterdam
      BACKEND_ADDRESS: http://music:8080
